language: node_js
node_js:
- '0.12'
- '4'
#- iojs
env:
- COVERAGE=true
- COVERAGE=false
matrix:
  exclude:
    node_js: 'iojs'

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - gcc --version
  - g++ --version

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
notifications:
  slack:
    secure: UYwnLYQ+Zt3BGQpYg4uWcbI8cs5+iWh1CWyvrMkYsnJ5vnyuF02kNWhpegawFqy6O0rEbOPcvgw+rsmr2a7x7SIHQ4Ej19rnbIHZEGJDJwd636FnCLzzS9m1fwmAa2cbIa0VufzTyrJwiibC05l31J9/mfSXwo7yZEmPahmlstU=
